Repository AY2021S2-CS2103T-W15-3/tp, pull requests merged in 2021-03, with the labels that each got.

#23 Remove traces of AB3 from config
  docs/_config.yml
Labels: question, type.Documentation

#28 Update NFRs, glossary
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Documentation

#48 modify components and corresponding parsers
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/inventory/InventoryDeleteCommand.java
  src/main/java/seedu/address/logic/commands/menu/MenuDeleteCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderDeleteCommand.java
  src/main/java/seedu/address/logic/commands/shopping/ShoppingDeleteCommand.java
  src/main/java/seedu/address/logic/parser/components/InventoryParser.java
  src/main/java/seedu/address/logic/parser/components/MenuParser.java
  src/main/java/seedu/address/logic/parser/components/OrderParser.java
  src/main/java/seedu/address/logic/parser/components/ShoppingParser.java
Labels: priority.Medium, type.Story

#53 Add add command
  src/main/java/seedu/address/logic/commands/inventory/InventoryAddCommand.java
  src/main/java/seedu/address/logic/commands/menu/MenuAddCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderAddCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/commands/inventory/InventoryAddCommandParser.java
  src/main/java/seedu/address/logic/parser/commands/menu/MenuAddCommandParser.java
  src/main/java/seedu/address/logic/parser/commands/order/OrderAddCommandParser.java
  src/main/java/seedu/address/logic/parser/components/InventoryParser.java
  src/main/java/seedu/address/logic/parser/components/MenuParser.java
  src/main/java/seedu/address/logic/parser/components/OrderParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/dish/Dish.java
  src/main/java/seedu/address/model/order/Order.java
Labels: priority.Medium

#84 Update List feature to use ENUMS
  src/main/.gradle/6.7.1/fileChanges/last-build.bin
  src/main/.gradle/6.7.1/fileHashes/fileHashes.lock
  src/main/.gradle/6.7.1/gc.properties
  src/main/.gradle/checksums/checksums.lock
  src/main/.gradle/configuration-cache/gc.properties
  src/main/.gradle/vcs-1/gc.properties
  src/main/java/seedu/address/commons/core/Pair.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/customer/CustomerAddCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerClearCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerFindCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerListCommand.java
  src/main/java/seedu/address/logic/commands/inventory/InventoryAddCommand.java
  src/main/java/seedu/address/logic/commands/inventory/InventoryDeleteCommand.java
  src/main/java/seedu/address/logic/commands/inventory/InventoryListCommand.java
  src/main/java/seedu/address/logic/commands/menu/MenuAddCommand.java
  src/main/java/seedu/address/logic/commands/menu/MenuDeleteCommand.java
  src/main/java/seedu/address/logic/commands/menu/MenuListCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderAddCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderDeleteCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderListCommand.java
  src/main/java/seedu/address/logic/commands/shopping/ShoppingAddCommand.java
  src/main/java/seedu/address/logic/commands/shopping/ShoppingDeleteCommand.java
  src/main/java/seedu/address/logic/commands/shopping/ShoppingListCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Medium

#88 1.3 DG update
  docs/DeveloperGuide.md
  docs/images/ShowMenuList.png
Labels: priority.Medium

#94 add assertions to deletePerson to confirm cascading delete
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.Low, type.Testing

#95 add logging for cascading delete of customers
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.Low

#96 add Assertion to list ocmmand
  src/main/java/seedu/address/ui/MainWindow.java
Labels: enhancement

#104 add lookup methods to Model.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/dish/Aggregator.java
  src/main/java/seedu/address/model/dish/Dish.java
  src/test/java/seedu/address/logic/commands/CustomerAddCommandTest.java
Labels: priority.Medium, type.Utility

#105 modify developer guide for week 10
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Documentation

#109 1.3b order list sorted by datetime
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/inventory/InventoryListCommand.java
  src/main/java/seedu/address/logic/commands/menu/MenuListCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderAddCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderListCommand.java
  src/main/java/seedu/address/logic/parser/commands/order/OrderAddCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UniqueItemList.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/OrderBook.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/InventoryListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MenuListPanel.java
  src/main/java/seedu/address/ui/OrderListPanel.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CustomerAddCommandTest.java
  src/test/java/seedu/address/logic/commands/CustomerDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/CustomerEditCommandTest.java
  src/test/java/seedu/address/logic/parser/CustomerAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CustomerEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/JJIMYParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonPersonBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializablePersonBookTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.Medium

#113 add order history command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/order/OrderHistoryCommand.java
  src/main/java/seedu/address/logic/parser/components/OrderParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/OrderBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CustomerAddCommandTest.java
Labels: priority.Medium

#119 add cascading deletion data link for deleting menu items
  src/main/java/seedu/address/logic/commands/menu/MenuDeleteCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/Aggregator.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/dish/Dish.java
  src/main/java/seedu/address/model/order/Order.java
  src/test/java/seedu/address/logic/commands/CustomerAddCommandTest.java
Labels: priority.High

#122 modify menu delete command to cancel instead of delete order
  src/main/java/seedu/address/logic/commands/menu/MenuDeleteCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CustomerAddCommandTest.java
Labels: priority.High
