Repository AY2021S2-CS2103T-W15-3/tp, pull requests merged in 2021-04, with the labels that each got.

#126 Implement edit command
  src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java
  src/main/java/seedu/address/logic/commands/inventory/InventoryEditCommand.java
  src/main/java/seedu/address/logic/commands/menu/MenuAddCommand.java
  src/main/java/seedu/address/logic/commands/menu/MenuCommandUtil.java
  src/main/java/seedu/address/logic/commands/menu/MenuEditCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderAddCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderCommandUtil.java
  src/main/java/seedu/address/logic/commands/order/OrderEditCommand.java
  src/main/java/seedu/address/logic/parser/commands/inventory/InventoryEditCommandParser.java
  src/main/java/seedu/address/logic/parser/commands/menu/MenuAddCommandParser.java
  src/main/java/seedu/address/logic/parser/commands/menu/MenuEditCommandParser.java
  src/main/java/seedu/address/logic/parser/commands/order/OrderAddCommandParser.java
  src/main/java/seedu/address/logic/parser/commands/order/OrderEditCommandParser.java
  src/main/java/seedu/address/logic/parser/components/InventoryParser.java
  src/main/java/seedu/address/logic/parser/components/MenuParser.java
  src/main/java/seedu/address/logic/parser/components/OrderParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium

#129 Filtered order list updating
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/order/OrderAddCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderCompleteCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderDeleteCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderEditCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderFindCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderHistoryCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderListCommand.java
  src/main/java/seedu/address/logic/parser/components/MenuParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/dish/DishContainsIngredientNamePredicate.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CustomerAddCommandTest.java
Labels: priority.Low

#135 add warning before cascading deletion of customer
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java
  src/main/java/seedu/address/logic/commands/menu/MenuDeleteCommand.java
  src/main/java/seedu/address/logic/parser/commands/customer/CustomerDeleteCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CustomerAddCommandTest.java
Labels: priority.Medium, type.DataLink

#138 Validate that orders can be fulfilled
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/logic/commands/menu/MenuListCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderAddCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderCommandUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ingredient/IngredientBook.java
  src/main/java/seedu/address/model/ingredient/ReadOnlyIngredientBook.java
  src/main/java/seedu/address/model/order/Order.java
  src/test/java/seedu/address/logic/commands/CustomerAddCommandTest.java
Labels: type.DataLink

#139 Update UserGuide.md
  docs/UserGuide.md
Labels: enhancement

#141 add function to toggle menu visibility
  src/main/java/seedu/address/logic/commands/menu/MenuListAvailableCommand.java
  src/main/java/seedu/address/logic/commands/menu/MenuListCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderCommandUtil.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/commands/menu/MenuListCommandParser.java
  src/main/java/seedu/address/logic/parser/components/MenuParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ingredient/IngredientBook.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Low

#142 Fixed issue with incorrect menu item creation logic
  src/main/java/seedu/address/logic/commands/menu/MenuCommandUtil.java
Labels: bug

#145 Update UG with examples for Customer commands
  docs/UserGuide.md
Labels: type.Documentation

#150 Add dropdown, darkmode, colorcode to User Guide
  docs/DeveloperGuide.md
  docs/Gemfile
  docs/UserGuide.md
  docs/_config.yml
  docs/assets/css/style.scss
  docs/images/github-icon.png
  docs/images/up.png
  src/main/java/seedu/address/logic/commands/order/OrderAddCommand.java
  src/main/java/seedu/address/logic/parser/commands/order/OrderEditCommandParser.java
Labels: type.Documentation

#216 Fix invalid menu items in sample data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium

#221 Modify `ModelManager::setPerson` update orders
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/order/Order.java
Labels: priority.High, type.DataLink

#222 Fix error message for `inventory delete` command
  src/main/java/seedu/address/logic/parser/commands/inventory/InventoryEditCommandParser.java
Labels: bug, priority.Medium

#231 Update PPP and UG
  docs/UserGuide.md
  docs/team/johndoe.md
  docs/team/kangtinglee.md
Labels: type.Documentation

#245 Added check on updated orders to ensure sufficient inventory to fulfil order
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderAddCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderEditCommand.java
  src/main/java/seedu/address/logic/parser/JJIMYParser.java
  src/main/java/seedu/address/logic/parser/components/CustomerParser.java
  src/main/java/seedu/address/logic/parser/components/InventoryParser.java
  src/main/java/seedu/address/logic/parser/components/MenuParser.java
  src/main/java/seedu/address/logic/parser/components/OrderParser.java
  src/main/java/seedu/address/model/Aggregator.java
  src/main/java/seedu/address/model/dish/Dish.java
  src/main/java/seedu/address/model/order/Order.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/JJIMYParserTest.java
Labels: bug

#253 Fix JSON parser errors for Order book
  src/main/java/seedu/address/logic/commands/order/OrderAddCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderEditCommand.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: bug

#261 Fix unchecked `menu edit` commands
  build.gradle
  src/main/java/seedu/address/logic/commands/menu/MenuDeleteCommand.java
  src/main/java/seedu/address/logic/commands/menu/MenuEditCommand.java
  src/main/java/seedu/address/logic/commands/order/OrderCommandUtil.java
  src/main/java/seedu/address/logic/commands/order/OrderEditCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/order/OrderBook.java
  src/test/java/seedu/address/logic/commands/CustomerAddCommandTest.java
Labels: bug, type.DataLink

#265 Resolve `menu edit` failure
  src/main/java/seedu/address/logic/commands/menu/MenuEditCommand.java
Labels: bug

#274 Updated DG datalinks section
  docs/DeveloperGuide.md
  docs/diagrams/EditDishObject.puml
  docs/images/EditDishObject.png
  src/main/java/seedu/address/logic/commands/menu/MenuDeleteCommand.java
Labels: type.Documentation

#277 DG and UG Updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#280 Update UG and DG v1.4
  docs/DeveloperGuide.md
  docs/team/kangtinglee.md
Labels: type.Documentation

#287 DG Final Updates
  docs/DeveloperGuide.md
  docs/SettingUp.md
Labels: type.Documentation
